### ISSUE TITLE
Improved ReadMe

### ISSUE THREAD

**Issue by UsmanAhmadSaeed** [UsmanAhmadSaeed/Animations#14]
With the request for landing page and separate contributions guideline, it'd be necessary to update and improve the ReadMe to include more information about Animations, Open-Source, and relevant information about this repo, etc.

**Comment by AbogeJr** [comment]
Hey.I'd like to work on this. May I?

**Comment by UsmanAhmadSaeed** [comment]
PR #17 by @Namrata-J closes this. 
Any further improvements are welcome
