### ISSUE TITLE
Update/Delete README.MD from folders other than root

### ISSUE THREAD

**Issue by UsmanAhmadSaeed** [UsmanAhmadSaeed/Animations#21]
### Issue
Almost all the folders contain a generic readme.md file

### Required
Update the README.MD files with information of relevant folder, or delete these files from all folders other than root.

**Comment by NguyenLyy** [comment]
I want to do it. Can you guide me?

**Comment by UsmanAhmadSaeed** [comment]
@NguyenLyy sorry, missed the notification. Yes, first of all, follow the contribution guidelines from this
https://github.com/UsmanAhmadSaeed/Animations#contribution-guidelines

After that, you can either delete the README.md files from all folders except the main/root folder.
Or you can update each folder's README.md so that it represents information on what is available within that folder.
For example, README.md file in "Scroll Animations" folder should contain a description of that folder, i.e. what that folder contains, and the acceptable code to be contributed in that folder, etc.

I'm open to suggestions on which approach to take to maintain this repository in the long run in a clean manner.
Personally, I think keeping so many markdown files is extensive and inefficient, and we could rather create a website that describes different sections, and organize main README.md to include all the necessary information.

**Comment by bumpylumps** [comment]
I'd be happy to help update those README.md files if you still need someone!

**Comment by UsmanAhmadSaeed** [comment]
@bumpylumps feel free to update these. It's not fully updated yet.

**Comment by PravarAnu** [comment]
Hey @UsmanAhmadSaeed  I will happy to do contribution for this issue. Can you please assign this issue to me.

**Comment by UsmanAhmadSaeed** [comment]
@PravarAnu please go ahead.

**Comment by SwatejReddy** [comment]
Can I take this up and delete all the README.md files except the root ones?
