### ISSUE TITLE
Add Animation links in Readme

### ISSUE THREAD

**Issue by UsmanAhmadSaeed** [UsmanAhmadSaeed/Animations#8]
[README.md](https://github.com/UsmanAhmadSaeed/Animations/blob/main/README.md) file needs to be updated with links to all animations inside repository folders, under *Animation Link* heading.
Use the already included link inside [README.md](https://github.com/UsmanAhmadSaeed/Animations/blob/main/README.md) for guidance.

**Comment by FishtheFish** [comment]
I'll snag this issue.
